export const currencies = [
  { "code": "AED", "symbol": "د.إ", "name": "United Arab Emirates Dirham", "flag": "🇦🇪" },
  { "code": "AFN", "symbol": "؋", "name": "Afghan Afghani", "flag": "🇦🇫" },
  { "code": "ALL", "symbol": "L", "name": "Albanian Lek", "flag": "🇦🇱" },
  { "code": "AMD", "symbol": "֏", "name": "Armenian Dram", "flag": "🇦🇲" },
  { "code": "AOA", "symbol": "Kz", "name": "Angolan Kwanza", "flag": "🇦🇴" },
  { "code": "ARS", "symbol": "$", "name": "Argentine Peso", "flag": "🇦🇷" },
  { "code": "AUD", "symbol": "$", "name": "Australian Dollar", "flag": "🇦🇺" },
  { "code": "AWG", "symbol": "ƒ", "name": "Aruban Florin", "flag": "🇦🇼" },
  { "code": "AZN", "symbol": "₼", "name": "Azerbaijani Manat", "flag": "🇦🇿" },
  { "code": "BAM", "symbol": "KM", "name": "Bosnia and Herzegovina Convertible Mark", "flag": "🇧🇦" },
  { "code": "BBD", "symbol": "$", "name": "Barbados Dollar", "flag": "🇧🇧" },
  { "code": "BDT", "symbol": "৳", "name": "Bangladeshi Taka", "flag": "🇧🇩" },
  { "code": "BGN", "symbol": "лв", "name": "Bulgarian Lev", "flag": "🇧🇬" },
  { "code": "BHD", "symbol": ".د.ب", "name": "Bahraini Dinar", "flag": "🇧🇭" },
  { "code": "BIF", "symbol": "FBu", "name": "Burundian Franc", "flag": "🇧🇮" },
  { "code": "BMD", "symbol": "$", "name": "Bermudian Dollar", "flag": "🇧🇲" },
  { "code": "BND", "symbol": "$", "name": "Brunei Dollar", "flag": "🇧🇳" },
  { "code": "BOB", "symbol": "Bs", "name": "Boliviano", "flag": "🇧🇴" },
  { "code": "BRL", "symbol": "R$", "name": "Brazilian Real", "flag": "🇧🇷" },
  { "code": "BSD", "symbol": "$", "name": "Bahamian Dollar", "flag": "🇧🇸" },
  { "code": "BTN", "symbol": "Nu.", "name": "Bhutanese Ngultrum", "flag": "🇧🇹" },
  { "code": "BWP", "symbol": "P", "name": "Botswana Pula", "flag": "🇧🇼" },
  { "code": "BYN", "symbol": "Br", "name": "Belarusian Ruble", "flag": "🇧🇾" },
  { "code": "BZD", "symbol": "$", "name": "Belize Dollar", "flag": "🇧🇿" },
  { "code": "CAD", "symbol": "$", "name": "Canadian Dollar", "flag": "🇨🇦" },
  { "code": "CDF", "symbol": "FC", "name": "Congolese Franc", "flag": "🇨🇩" },
  { "code": "CHF", "symbol": "Fr", "name": "Swiss Franc", "flag": "🇨🇭" },
  { "code": "CLP", "symbol": "$", "name": "Chilean Peso", "flag": "🇨🇱" },
  { "code": "CNY", "symbol": "¥", "name": "Chinese Yuan Renminbi", "flag": "🇨🇳" },
  { "code": "COP", "symbol": "$", "name": "Colombian Peso", "flag": "🇨🇴" },
  { "code": "CRC", "symbol": "₡", "name": "Costa Rican Colon", "flag": "🇨🇷" },
  { "code": "CUP", "symbol": "$", "name": "Cuban Peso", "flag": "🇨🇺" },
  { "code": "CVE", "symbol": "$", "name": "Cape Verdean Escudo", "flag": "🇨🇻" },
  { "code": "CZK", "symbol": "Kč", "name": "Czech Koruna", "flag": "🇨🇿" },
  { "code": "DJF", "symbol": "Fdj", "name": "Djiboutian Franc", "flag": "🇩🇯" },
  { "code": "DKK", "symbol": "kr", "name": "Danish Krone", "flag": "🇩🇰" },
  { "code": "DOP", "symbol": "$", "name": "Dominican Peso", "flag": "🇩🇴" },
  { "code": "DZD", "symbol": "د.ج", "name": "Algerian Dinar", "flag": "🇩🇿" },
  { "code": "EGP", "symbol": "£", "name": "Egyptian Pound", "flag": "🇪🇬" },
  { "code": "ERN", "symbol": "Nfk", "name": "Eritrean Nakfa", "flag": "🇪🇷" },
  { "code": "ETB", "symbol": "Br", "name": "Ethiopian Birr", "flag": "🇪🇹" },
  { "code": "EUR", "symbol": "€", "name": "Euro", "flag": "🇪🇺" },
  { "code": "FJD", "symbol": "$", "name": "Fiji Dollar", "flag": "🇫🇯" },
  { "code": "FKP", "symbol": "£", "name": "Falkland Islands Pound", "flag": "🇫🇰" },
  { "code": "GBP", "symbol": "£", "name": "British Pound Sterling", "flag": "🇬🇧" },
  { "code": "GEL", "symbol": "₾", "name": "Georgian Lari", "flag": "🇬🇪" },
  { "code": "GHS", "symbol": "₵", "name": "Ghanaian Cedi", "flag": "🇬🇭" },
  { "code": "GIP", "symbol": "£", "name": "Gibraltar Pound", "flag": "🇬🇮" },
  { "code": "GMD", "symbol": "D", "name": "Gambian Dalasi", "flag": "🇬🇲" },
  { "code": "GNF", "symbol": "FG", "name": "Guinean Franc", "flag": "🇬🇳" },
  { "code": "GTQ", "symbol": "Q", "name": "Guatemalan Quetzal", "flag": "🇬🇹" },
  { "code": "GYD", "symbol": "$", "name": "Guyanese Dollar", "flag": "🇬🇾" },
  { "code": "HKD", "symbol": "$", "name": "Hong Kong Dollar", "flag": "🇭🇰" },
  { "code": "HNL", "symbol": "L", "name": "Honduran Lempira", "flag": "🇭🇳" },
  { "code": "HRK", "symbol": "kn", "name": "Croatian Kuna", "flag": "🇭🇷" },
  { "code": "HTG", "symbol": "G", "name": "Haitian Gourde", "flag": "🇭🇹" },
  { "code": "HUF", "symbol": "Ft", "name": "Hungarian Forint", "flag": "🇭🇺" },
  { "code": "IDR", "symbol": "Rp", "name": "Indonesian Rupiah", "flag": "🇮🇩" },
  { "code": "ILS", "symbol": "₪", "name": "Israeli New Shekel", "flag": "🇮🇱" },
  { "code": "INR", "symbol": "₹", "name": "Indian Rupee", "flag": "🇮🇳" },
  { "code": "IQD", "symbol": "ع.د", "name": "Iraqi Dinar", "flag": "🇮🇶" },
  { "code": "IRR", "symbol": "﷼", "name": "Iranian Rial", "flag": "🇮🇷" },
  { "code": "ISK", "symbol": "kr", "name": "Icelandic Króna", "flag": "🇮🇸" },
  { "code": "JMD", "symbol": "$", "name": "Jamaican Dollar", "flag": "🇯🇲" },
  { "code": "JOD", "symbol": "د.ا", "name": "Jordanian Dinar", "flag": "🇯🇴" },
  { "code": "JPY", "symbol": "¥", "name": "Japanese Yen", "flag": "🇯🇵" },
  { "code": "KES", "symbol": "KSh", "name": "Kenyan Shilling", "flag": "🇰🇪" },
  { "code": "KGS", "symbol": "лв", "name": "Kyrgyzstani Som", "flag": "🇰🇬" },
  { "code": "KHR", "symbol": "៛", "name": "Cambodian Riel", "flag": "🇰🇭" },
  { "code": "KMF", "symbol": "CF", "name": "Comoro Franc", "flag": "🇰🇲" },
  { "code": "KPW", "symbol": "₩", "name": "North Korean Won", "flag": "🇰🇵" },
  { "code": "KRW", "symbol": "₩", "name": "South Korean Won", "flag": "🇰🇷" },
  { "code": "KWD", "symbol": "د.ك", "name": "Kuwaiti Dinar", "flag": "🇰🇼" },
  { "code": "KYD", "symbol": "$", "name": "Cayman Islands Dollar", "flag": "🇰🇾" },
  { "code": "KZT", "symbol": "₸", "name": "Kazakhstani Tenge", "flag": "🇰🇿" },
  { "code": "LAK", "symbol": "₭", "name": "Lao Kip", "flag": "🇱🇦" },
  { "code": "LBP", "symbol": "ل.ل", "name": "Lebanese Pound", "flag": "🇱🇧" },
  { "code": "LKR", "symbol": "Rs", "name": "Sri Lankan Rupee", "flag": "🇱🇰" },
  { "code": "LRD", "symbol": "$", "name": "Liberian Dollar", "flag": "🇱🇷" },
  { "code": "LSL", "symbol": "L", "name": "Lesotho Loti", "flag": "🇱🇸" },
  { "code": "LYD", "symbol": "ل.د", "name": "Libyan Dinar", "flag": "🇱🇾" },
  { "code": "MAD", "symbol": "د.م.", "name": "Moroccan Dirham", "flag": "🇲🇦" },
  { "code": "MDL", "symbol": "L", "name": "Moldovan Leu", "flag": "🇲🇩" },
  { "code": "MGA", "symbol": "Ar", "name": "Malagasy Ariary", "flag": "🇲🇬" },
  { "code": "MKD", "symbol": "ден", "name": "Macedonian Denar", "flag": "🇲🇰" },
  { "code": "MMK", "symbol": "Ks", "name": "Myanmar Kyat", "flag": "🇲🇲" },
  { "code": "MNT", "symbol": "₮", "name": "Mongolian Tögrög", "flag": "🇲🇳" },
  { "code": "MOP", "symbol": "P", "name": "Macanese Pataca", "flag": "🇲🇴" },
  { "code": "MRU", "symbol": "UM", "name": "Mauritanian Ouguiya", "flag": "🇲🇷" },
  { "code": "MUR", "symbol": "₨", "name": "Mauritian Rupee", "flag": "🇲🇺" },
  { "code": "MVR", "symbol": "Rf", "name": "Maldivian Rufiyaa", "flag": "🇲🇻" },
  { "code": "MWK", "symbol": "MK", "name": "Malawian Kwacha", "flag": "🇲🇼" },
  { "code": "MXN", "symbol": "$", "name": "Mexican Peso", "flag": "🇲🇽" },
  { "code": "MYR", "symbol": "RM", "name": "Malaysian Ringgit", "flag": "🇲🇾" },
  { "code": "MZN", "symbol": "MT", "name": "Mozambican Metical", "flag": "🇲🇿" },
  { "code": "NAD", "symbol": "$", "name": "Namibian Dollar", "flag": "🇳🇦" },
  { "code": "NGN", "symbol": "₦", "name": "Nigerian Naira", "flag": "🇳🇬" },
  { "code": "NIO", "symbol": "C$", "name": "Nicaraguan Córdoba", "flag": "🇳🇮" },
  { "code": "NOK", "symbol": "kr", "name": "Norwegian Krone", "flag": "🇳🇴" },
  { "code": "NPR", "symbol": "₨", "name": "Nepalese Rupee", "flag": "🇳🇵" },
  { "code": "NZD", "symbol": "$", "name": "New Zealand Dollar", "flag": "🇳🇿" },
  { "code": "OMR", "symbol": "﷼", "name": "Omani Rial", "flag": "🇴🇲" },
  { "code": "PAB", "symbol": "B/.", "name": "Panamanian Balboa", "flag": "🇵🇦" },
  { "code": "PEN", "symbol": "S/", "name": "Peruvian Sol", "flag": "🇵🇪" },
  { "code": "PGK", "symbol": "K", "name": "Papua New Guinean Kina", "flag": "🇵🇬" },
  { "code": "PHP", "symbol": "₱", "name": "Philippine Peso", "flag": "🇵🇭" },
  { "code": "PKR", "symbol": "₨", "name": "Pakistani Rupee", "flag": "🇵🇰" },
  { "code": "PLN", "symbol": "zł", "name": "Polish Złoty", "flag": "🇵🇱" },
  { "code": "PYG", "symbol": "₲", "name": "Paraguayan Guaraní", "flag": "🇵🇾" },
  { "code": "QAR", "symbol": "﷼", "name": "Qatari Riyal", "flag": "🇶🇦" },
  { "code": "RON", "symbol": "lei", "name": "Romanian Leu", "flag": "🇷🇴" },
  { "code": "RSD", "symbol": "дин", "name": "Serbian Dinar", "flag": "🇷🇸" },
  { "code": "RUB", "symbol": "₽", "name": "Russian Ruble", "flag": "🇷🇺" },
  { "code": "RWF", "symbol": "FRw", "name": "Rwandan Franc", "flag": "🇷🇼" },
  { "code": "SAR", "symbol": "﷼", "name": "Saudi Riyal", "flag": "🇸🇦" },
  { "code": "SBD", "symbol": "$", "name": "Solomon Islands Dollar", "flag": "🇸🇧" },
  { "code": "SCR", "symbol": "₨", "name": "Seychelles Rupee", "flag": "🇸🇨" },
  { "code": "SDG", "symbol": "£", "name": "Sudanese Pound", "flag": "🇸🇩" },
  { "code": "SEK", "symbol": "kr", "name": "Swedish Krona", "flag": "🇸🇪" },
  { "code": "SGD", "symbol": "$", "name": "Singapore Dollar", "flag": "🇸🇬" },
  { "code": "SHP", "symbol": "£", "name": "Saint Helena Pound", "flag": "🇸🇭" },
  { "code": "SLE", "symbol": "Le", "name": "Sierra Leonean Leone", "flag": "🇸🇱" },
  { "code": "SOS", "symbol": "Sh", "name": "Somali Shilling", "flag": "🇸🇴" },
  { "code": "SRD", "symbol": "$", "name": "Surinamese Dollar", "flag": "🇸🇷" },
  { "code": "SSP", "symbol": "£", "name": "South Sudanese Pound", "flag": "🇸🇸" },
  { "code": "STN", "symbol": "Db", "name": "São Tomé and Príncipe Dobra", "flag": "🇸🇹" },
  { "code": "SVC", "symbol": "₡", "name": "Salvadoran Colón", "flag": "🇸🇻" },
  { "code": "SYP", "symbol": "£", "name": "Syrian Pound", "flag": "🇸🇾" },
  { "code": "SZL", "symbol": "L", "name": "Swazi Lilangeni", "flag": "🇸🇿" },
  { "code": "THB", "symbol": "฿", "name": "Thai Baht", "flag": "🇹🇭" },
  { "code": "TJS", "symbol": "ЅМ", "name": "Tajikistani Somoni", "flag": "🇹🇯" },
  { "code": "TMT", "symbol": "m", "name": "Turkmenistan Manat", "flag": "🇹🇲" },
  { "code": "TND", "symbol": "د.ت", "name": "Tunisian Dinar", "flag": "🇹🇳" },
  { "code": "TOP", "symbol": "T$", "name": "Tongan Paʻanga", "flag": "🇹🇴" },
  { "code": "TRY", "symbol": "₺", "name": "Turkish Lira", "flag": "🇹🇷" },
  { "code": "TTD", "symbol": "$", "name": "Trinidad and Tobago Dollar", "flag": "🇹🇹" },
  { "code": "TWD", "symbol": "NT$", "name": "New Taiwan Dollar", "flag": "🇹🇼" },
  { "code": "TZS", "symbol": "Sh", "name": "Tanzanian Shilling", "flag": "🇹🇿" },
  { "code": "UAH", "symbol": "₴", "name": "Ukrainian Hryvnia", "flag": "🇺🇦" },
  { "code": "UGX", "symbol": "Sh", "name": "Ugandan Shilling", "flag": "🇺🇬" },
  { "code": "USD", "symbol": "$", "name": "United States Dollar", "flag": "🇺🇸" },
  { "code": "UYU", "symbol": "$", "name": "Uruguayan Peso", "flag": "🇺🇾" },
  { "code": "UZS", "symbol": "сўм", "name": "Uzbekistani Som", "flag": "🇺🇿" },
  { "code": "VES", "symbol": "Bs.S", "name": "Venezuelan Bolívar Soberano", "flag": "🇻🇪" },
  { "code": "VND", "symbol": "₫", "name": "Vietnamese Đồng", "flag": "🇻🇳" },
  { "code": "VUV", "symbol": "Vt", "name": "Vanuatu Vatu", "flag": "🇻🇺" },
  { "code": "WST", "symbol": "T", "name": "Samoan Tala", "flag": "🇼🇸" },
  { "code": "XCD", "symbol": "$", "name": "East Caribbean Dollar", "flag": "🇦🇮" },
  { "code": "XOF", "symbol": "CFA", "name": "CFA Franc BCEAO", "flag": "🇧🇯" },
  { "code": "XPF", "symbol": "₣", "name": "CFP Franc", "flag": "🇵🇫" },
  { "code": "YER", "symbol": "﷼", "name": "Yemeni Rial", "flag": "🇾🇪" },
  { "code": "ZAR", "symbol": "R", "name": "South African Rand", "flag": "🇿🇦" },
  { "code": "ZMW", "symbol": "ZK", "name": "Zambian Kwacha", "flag": "🇿🇲" },
  { "code": "ZWL", "symbol": "$", "name": "Zimbabwe Dollar", "flag": "🇿🇼" }
];
